spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/caught_up_dev
spring.datasource.username=${SPRING_DATASOURCE_DEV_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_DEV_PASSWORD}

spring.data.redis.database=0

#logging.level.com.kwsni.caught_up.tvdb=debug
#logging.level.com.kwsni.caught_up.config=debug
#logging.level.org.springframework.batch=debug
#logging.level.org.springframework.jdbc=debug
#logging.level.SQL=debug
#logging.level.org.hibernate.orm.jdbc.bind=trace

logging.file.name=logs/caught_up_dev.log