spring.application.name=caught_up
spring.profiles.active=prod
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.batch.job.enabled=false
spring.threads.virtual.enabled=true
spring.servlet.multipart.max-file-size=10MB

tvdb.api.api_key=${TVDB_API_KEY}
tvdb.api.base_url=${TVDB_BASE_URL}
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.batch.jdbc.initialize-schema=never
