spring.application.name=caught_up
spring.profiles.active=prod
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.batch.job.enabled=false
#spring.batch.job.name=tvdbInitialSyncJob
tvdb.api.api_key=${TVDB_API_KEY}
tvdb.api.base_url=${TVDB_BASE_URL}

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
