-- liquibase formatted sql

-- changeset root:1778137177014-1 splitStatements:false
CREATE TABLE "member" ("avatar" VARCHAR(255) DEFAULT 'https://cdn.discordapp.com/embed/avatars/1.png', "bio" VARCHAR(255), "first_name" VARCHAR(255), "last_name" VARCHAR(255), "location" VARCHAR(255), "pronoun" VARCHAR(255), "website" VARCHAR(255), "id" BIGINT NOT NULL, "is_generated" BOOLEAN DEFAULT FALSE, "password" VARCHAR(255), "role" VARCHAR(255), "email" VARCHAR(255), "username" VARCHAR(255), CONSTRAINT "member_pkey" PRIMARY KEY ("id"));

-- changeset root:1778137177014-2 splitStatements:false
CREATE TABLE "episode" ("tvdb_id" BIGINT NOT NULL, "absolute_number" INTEGER, "aired" VARCHAR(255), "airs_after_season" INTEGER, "airs_before_episode" INTEGER, "airs_before_season" INTEGER, "image" VARCHAR(255), "image_type" INTEGER, "is_movie" BIGINT, "name" VARCHAR(255), "number" INTEGER, "overview" TEXT, "runtime" INTEGER, "season_name" VARCHAR(255), "season_number" INTEGER, "year" VARCHAR(255), "series_tvdb_id" BIGINT, CONSTRAINT "episode_pkey" PRIMARY KEY ("tvdb_id"));

-- changeset root:1778137177014-3 splitStatements:false
CREATE TABLE "review" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "content" TEXT, "created_date" TIMESTAMP WITHOUT TIME ZONE, "is_spoiler" BOOLEAN NOT NULL, "member_id" BIGINT, "series_tvdb_id" BIGINT, "liked" BOOLEAN NOT NULL, "watched_date" TIMESTAMP WITH TIME ZONE, "rating" FLOAT8, "is_generated" BOOLEAN NOT NULL, CONSTRAINT "review_pkey" PRIMARY KEY ("id"));

-- changeset root:1778137177014-4 splitStatements:false
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(255) NOT NULL, "password" VARCHAR(255), "role" VARCHAR(255), "username" VARCHAR(255) NOT NULL, "is_generated" BOOLEAN DEFAULT FALSE, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset root:1778137177014-5 splitStatements:false
CREATE TABLE "batch_job_instance" ("job_instance_id" BIGINT NOT NULL, "version" BIGINT, "job_name" VARCHAR(100) NOT NULL, "job_key" VARCHAR(32) NOT NULL, CONSTRAINT "batch_job_instance_pkey" PRIMARY KEY ("job_instance_id"));

-- changeset root:1778137177014-6 splitStatements:false
CREATE INDEX "idx5fqsfsx4jf6x424sv7o5eth6p" ON "episode" USING btree("series_tvdb_id", "season_number");

-- changeset root:1778137177014-7 splitStatements:false
CREATE INDEX "fki_F" ON "episode" USING btree("series_tvdb_id");

-- changeset root:1778137177014-8 splitStatements:false
CREATE INDEX "fki_foreign_key_series_id" ON "review" USING btree("series_tvdb_id");

-- changeset root:1778137177014-9 splitStatements:false
ALTER TABLE "batch_job_instance" ADD CONSTRAINT "job_inst_un" UNIQUE ("job_name", "job_key");

-- changeset root:1778137177014-10 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "batch_job_execution_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-11 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "batch_job_instance_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-12 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "batch_job_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-13 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "batch_step_execution_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-14 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "company_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-15 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "episode_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-16 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "season_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-17 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "series_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-18 splitStatements:false
CREATE SEQUENCE  IF NOT EXISTS "users_seq" AS bigint START WITH 1 INCREMENT BY 50 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- changeset root:1778137177014-19 splitStatements:false
CREATE TABLE "batch_job_execution" ("job_execution_id" BIGINT NOT NULL, "version" BIGINT, "job_instance_id" BIGINT NOT NULL, "create_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "start_time" TIMESTAMP WITHOUT TIME ZONE, "end_time" TIMESTAMP WITHOUT TIME ZONE, "status" VARCHAR(10), "exit_code" VARCHAR(2500), "exit_message" VARCHAR(2500), "last_updated" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "batch_job_execution_pkey" PRIMARY KEY ("job_execution_id"));

-- changeset root:1778137177014-20 splitStatements:false
CREATE TABLE "batch_job_execution_context" ("job_execution_id" BIGINT NOT NULL, "short_context" VARCHAR(2500) NOT NULL, "serialized_context" TEXT, CONSTRAINT "batch_job_execution_context_pkey" PRIMARY KEY ("job_execution_id"));

-- changeset root:1778137177014-21 splitStatements:false
CREATE TABLE "batch_job_execution_params" ("job_execution_id" BIGINT NOT NULL, "parameter_name" VARCHAR(100) NOT NULL, "parameter_type" VARCHAR(100) NOT NULL, "parameter_value" VARCHAR(2500), "identifying" CHAR(1) NOT NULL);

-- changeset root:1778137177014-22 splitStatements:false
CREATE TABLE "batch_step_execution" ("step_execution_id" BIGINT NOT NULL, "version" BIGINT NOT NULL, "step_name" VARCHAR(100) NOT NULL, "job_execution_id" BIGINT NOT NULL, "create_time" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "start_time" TIMESTAMP WITHOUT TIME ZONE, "end_time" TIMESTAMP WITHOUT TIME ZONE, "status" VARCHAR(10), "commit_count" BIGINT, "read_count" BIGINT, "filter_count" BIGINT, "write_count" BIGINT, "read_skip_count" BIGINT, "write_skip_count" BIGINT, "process_skip_count" BIGINT, "rollback_count" BIGINT, "exit_code" VARCHAR(2500), "exit_message" VARCHAR(2500), "last_updated" TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT "batch_step_execution_pkey" PRIMARY KEY ("step_execution_id"));

-- changeset root:1778137177014-23 splitStatements:false
CREATE TABLE "batch_step_execution_context" ("step_execution_id" BIGINT NOT NULL, "short_context" VARCHAR(2500) NOT NULL, "serialized_context" TEXT, CONSTRAINT "batch_step_execution_context_pkey" PRIMARY KEY ("step_execution_id"));

-- changeset root:1778137177014-24 splitStatements:false
CREATE TABLE "member_follow" ("follow_date" TIMESTAMP WITHOUT TIME ZONE, "followed_id" BIGINT NOT NULL, "follower_id" BIGINT NOT NULL, CONSTRAINT "member_follow_pkey" PRIMARY KEY ("followed_id", "follower_id"));

-- changeset root:1778137177014-25 splitStatements:false
CREATE TABLE "review_comment" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "content" TEXT, "created_date" TIMESTAMP WITH TIME ZONE, "member_id" BIGINT, "review_id" BIGINT, CONSTRAINT "review_comment_pkey" PRIMARY KEY ("id"));

-- changeset root:1778137177014-26 splitStatements:false
CREATE TABLE "review_comment_like" ("review_comment_id" BIGINT NOT NULL, "member_id" BIGINT NOT NULL, CONSTRAINT "review_comment_like_pkey" PRIMARY KEY ("review_comment_id", "member_id"));

-- changeset root:1778137177014-27 splitStatements:false
CREATE TABLE "review_like" ("review_id" BIGINT NOT NULL, "member_id" BIGINT NOT NULL, CONSTRAINT "review_like_pkey" PRIMARY KEY ("review_id", "member_id"));

-- changeset root:1778137177014-28 splitStatements:false
CREATE TABLE "series" ("tvdb_id" BIGINT NOT NULL, "country" VARCHAR(255), "first_aired" VARCHAR(255), "image" VARCHAR(255), "last_aired" VARCHAR(255), "last_updated" VARCHAR(255), "name" VARCHAR(255), "next_aired" VARCHAR(255), "overview" TEXT, "score" FLOAT8, "slug" VARCHAR(255), "year" VARCHAR(255), CONSTRAINT "series_pkey" PRIMARY KEY ("tvdb_id"));

-- changeset root:1778137177014-29 splitStatements:false
CREATE TABLE "update_record" ("record_id" BIGINT NOT NULL, "entity_type" VARCHAR(255), "merge_to_id" BIGINT, "method" VARCHAR(255), "method_int" INTEGER, "merge_to_type" VARCHAR(255), "timestamp" BIGINT, CONSTRAINT "update_record_pkey" PRIMARY KEY ("record_id"));

-- changeset root:1778137177014-30 splitStatements:false
ALTER TABLE "review_like" ADD CONSTRAINT "fk68am9vk1s1e8n1v873meqkk0k" FOREIGN KEY ("review_id") REFERENCES "review" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-31 splitStatements:false
ALTER TABLE "review_comment" ADD CONSTRAINT "fk9j7pkcpuestrwjre1a1902biu" FOREIGN KEY ("review_id") REFERENCES "review" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-32 splitStatements:false
ALTER TABLE "review_comment_like" ADD CONSTRAINT "fkddrwbjykr7144ihgteim2gmiy" FOREIGN KEY ("member_id") REFERENCES "member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-33 splitStatements:false
ALTER TABLE "member" ADD CONSTRAINT "fkeog0m8jm2ck5j048aeswwrqcv" FOREIGN KEY ("id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-34 splitStatements:false
ALTER TABLE "review_like" ADD CONSTRAINT "fkf19ep4u0vm5vietilw2kp9jo2" FOREIGN KEY ("member_id") REFERENCES "member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-35 splitStatements:false
ALTER TABLE "review" ADD CONSTRAINT "fkk0ccx5i4ci2wd70vegug074w1" FOREIGN KEY ("member_id") REFERENCES "member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-36 splitStatements:false
ALTER TABLE "member_follow" ADD CONSTRAINT "fkpghhsrylibs34srueg1p0heu9" FOREIGN KEY ("followed_id") REFERENCES "member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-37 splitStatements:false
ALTER TABLE "review_comment" ADD CONSTRAINT "fkqwqh8uijvu4mvspob99au0tmh" FOREIGN KEY ("member_id") REFERENCES "member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-38 splitStatements:false
ALTER TABLE "review_comment_like" ADD CONSTRAINT "fkrcox1bv7k3wrfqc5a2d659noo" FOREIGN KEY ("review_comment_id") REFERENCES "review_comment" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-39 splitStatements:false
ALTER TABLE "member_follow" ADD CONSTRAINT "fkrshygjds7c4j7prtkkok4ax6p" FOREIGN KEY ("follower_id") REFERENCES "member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-40 splitStatements:false
ALTER TABLE "episode" ADD CONSTRAINT "foreign_key_series_id" FOREIGN KEY ("series_tvdb_id") REFERENCES "series" ("tvdb_id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset root:1778137177014-41 splitStatements:false
ALTER TABLE "review" ADD CONSTRAINT "foreign_key_series_id" FOREIGN KEY ("series_tvdb_id") REFERENCES "series" ("tvdb_id") ON UPDATE CASCADE ON DELETE SET NULL;

-- changeset root:1778137177014-42 splitStatements:false
ALTER TABLE "batch_job_execution_context" ADD CONSTRAINT "job_exec_ctx_fk" FOREIGN KEY ("job_execution_id") REFERENCES "batch_job_execution" ("job_execution_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-43 splitStatements:false
ALTER TABLE "batch_job_execution_params" ADD CONSTRAINT "job_exec_params_fk" FOREIGN KEY ("job_execution_id") REFERENCES "batch_job_execution" ("job_execution_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-44 splitStatements:false
ALTER TABLE "batch_step_execution" ADD CONSTRAINT "job_exec_step_fk" FOREIGN KEY ("job_execution_id") REFERENCES "batch_job_execution" ("job_execution_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-45 splitStatements:false
ALTER TABLE "batch_job_execution" ADD CONSTRAINT "job_inst_exec_fk" FOREIGN KEY ("job_instance_id") REFERENCES "batch_job_instance" ("job_instance_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset root:1778137177014-46 splitStatements:false
ALTER TABLE "batch_step_execution_context" ADD CONSTRAINT "step_exec_ctx_fk" FOREIGN KEY ("step_execution_id") REFERENCES "batch_step_execution" ("step_execution_id") ON UPDATE NO ACTION ON DELETE NO ACTION;

